//do not used repeated name cities in different provinces
//a minimun of 3 cities and provinces
const mycitiesandprovinces =  [
  { "city": "Bogotá", "province": "Cundinamarca" },
  { "city": "Soacha", "province": "Cundinamarca" },
  { "city": "Medellín", "province": "Antioquia" },
  { "city": "Bello", "province": "Antioquia" },
  { "city": "Itagüí", "province": "Antioquia" },
  { "city": "Envigado", "province": "Antioquia" },
  { "city": "Rionegro", "province": "Antioquia" },
  { "city": "Apartadó", "province": "Antioquia" },
  { "city": "Cali", "province": "Valle del Cauca" },
  { "city": "Palmira", "province": "Valle del Cauca" },
  { "city": "Buenaventura", "province": "Valle del Cauca" },
  { "city": "Tuluá", "province": "Valle del Cauca" },
  { "city": "Jamundí", "province": "Valle del Cauca" },
  { "city": "Cartago", "province": "Valle del Cauca" },
  { "city": "Barranquilla", "province": "Atlántico" },
  { "city": "Soledad", "province": "Atlántico" },
  { "city": "Malambo", "province": "Atlántico" },
  { "city": "Cartagena", "province": "Bolívar" },
  { "city": "Magangué", "province": "Bolívar" },
  { "city": "Turbaco", "province": "Bolívar" },
  { "city": "Bucaramanga", "province": "Santander" },
  { "city": "Floridablanca", "province": "Santander" },
  { "city": "Piedecuesta", "province": "Santander" },
  { "city": "Pereira", "province": "Risaralda" },
  { "city": "Dosquebradas", "province": "Risaralda" },
  { "city": "Santa Rosa de Cabal", "province": "Risaralda" },
  { "city": "Manizales", "province": "Caldas" },
  { "city": "Villamaría", "province": "Caldas" },
  { "city": "La Dorada", "province": "Caldas" },
  { "city": "Armenia", "province": "Quindío" },
  { "city": "Montenegro", "province": "Quindío" },
  { "city": "Calarcá", "province": "Quindío" },
  { "city": "Ibagué", "province": "Tolima" },
  { "city": "Espinal", "province": "Tolima" },
  { "city": "Melgar", "province": "Tolima" },
  { "city": "Cúcuta", "province": "Norte de Santander" },
  { "city": "Ocaña", "province": "Norte de Santander" },
  { "city": "Pamplona", "province": "Norte de Santander" },
  { "city": "Santa Marta", "province": "Magdalena" },
  { "city": "Ciénaga", "province": "Magdalena" },
  { "city": "Fundación", "province": "Magdalena" },
  { "city": "Popayán", "province": "Cauca" },
  { "city": "Santander de Quilichao", "province": "Cauca" },
  { "city": "Villavicencio", "province": "Meta" },
  { "city": "Granada", "province": "Meta" },
  { "city": "Montería", "province": "Córdoba" },
  { "city": "Cereté", "province": "Córdoba" },
  { "city": "Neiva", "province": "Huila" },
  { "city": "Pitalito", "province": "Huila" },
  { "city": "Valledupar", "province": "Cesar" },
  { "city": "Aguachica", "province": "Cesar" },
  { "city": "Sincelejo", "province": "Sucre" },
  { "city": "Corozal", "province": "Sucre" },
  { "city": "Tunja", "province": "Boyacá" },
  { "city": "Duitama", "province": "Boyacá" },
  { "city": "Sogamoso", "province": "Boyacá" },
  { "city": "Riohacha", "province": "La Guajira" },
  { "city": "Maicao", "province": "La Guajira" },
  { "city": "Quibdó", "province": "Chocó" },
  { "city": "Istmina", "province": "Chocó" },
  { "city": "Florencia", "province": "Caquetá" },
  { "city": "Leticia", "province": "Amazonas" },
  { "city": "San Andrés", "province": "San Andrés y Providencia" },
  { "city": "Yopal", "province": "Casanare" },
  { "city": "Mocoa", "province": "Putumayo" },
  { "city": "Puerto Carreño", "province": "Vichada" },
  { "city": "Inírida", "province": "Guainía" },
  { "city": "Mitú", "province": "Vaupés" },
  { "city": "Arauca", "province": "Arauca" }
]

  module.exports = mycitiesandprovinces;

 
  