

  const teachingOrdersArr = [
    {
      Name: 'Johnas Doe',
      Phone: '123-456-7890',
      Address: '123 Mains Street, Toronto, ON',
      Email: 'johndoeas@example.com',
      location: 'Toronto, ON',
      Subscription: false,
      PayFrequencySub: null,
      NextSubMaintdDate: null,
      TransactionValue: 199.99,
      TermsAgreed: 'Agreed to the standard terms and conditions.',
      ZoomID: 'ZOOM12345',
      TransactionRefNum1: 'TRANS12345',
      TransactionRefNum2: 'ALT12345',
    },
    {
      Name: 'Janesg Smiths',
      Phone: '987-654-3210',
      Address: '456 Elmswy Street, Mississauga, ON',
      Email: 'janesmidasfth@example.com',
      location: 'Mississauga, ON',
      Subscription: false,
      PayFrequencySub: null,
      NextSubMaintdDate: null,
      TransactionValue: 149.99,
      TermsAgreed: 'Agreed to the standard terms and conditions.',
      ZoomID: 'ZOOM54321',
      TransactionRefNum1: 'TRANS54321',
      TransactionRefNum2: null,
    },
    {
      Name: 'chlice Johnsones',
      Phone: '555-666-7777',
      Address: '789 Oaks Avenue, Oakville, ON',
      Email: 'alice45j@example.com',
      location: 'Oakville, ON',
      Subscription: false,
      PayFrequencySub: null,
      NextSubMaintdDate: null,
      TransactionValue: 999.99,
      TermsAgreed: 'Agreed to the extended service terms.',
      ZoomID: 'ZOOM67890',
      TransactionRefNum1: 'TRANS67890',
      TransactionRefNum2: 'ALT67890',
    },
    {
      Name: 'Bobrer Brown',
      Phone: '444-555-6666',
      Address: '321 Pines Lanes, Hamilton, ON',
      Email: 'bofrgrgbb@example.com',
      location: 'Hamilton, ON',
      Subscription: false,
      PayFrequencySub: null,
      NextSubMaintdDate: null,
      TransactionValue: 129.99,
      TermsAgreed: 'Agreed to the standard terms and conditions.',
      ZoomID: null,
      TransactionRefNum1: 'TRANS98765',
      TransactionRefNum2: null,
    },
  ];

  const MaintOrdeArr = [
    {
      Name: 'John Doer',
      Phone: '123-456-7890',
      Address: '123 Main Street, Toronto, ON',
      Email: 'johndoe@example.com',
      location: 'Toronto, ON',
      Subscription: false,
      PayFrequencySub: null,
      NextSubMaintdDate: null,
      TransactionValue: 199.99,
      TermsAgreed: 'Agreed to the standard terms and conditions.',
      TransactionRefNum1: 'TRANS12345',
      TransactionRefNum2: 'ALT12345',
          ProvinceID:'Cundinamarca', 
      CityID:'Bogotá'
    },
    {
      Name: 'Janeth Smith',
      Phone: '987-654-3210',
      Address: '456 Elm Street, Mississauga, ON',
      Email: 'johndoe@example.com',
      location: 'Mississauga, ON',
      Subscription: false,
      PayFrequencySub: null,
      NextSubMaintdDate: null,
      TransactionValue: 149.99,
      TermsAgreed: 'Agreed to the standard terms and conditions.',
      TransactionRefNum1: 'TRANS54321',
      TransactionRefNum2: null,
      ProvinceID:'Cundinamarca', 
      CityID:'Bogotá'
    },
    {
      Name: 'Aliceos Johnsons',
      Phone: '555-666-7777',
      Address: '789 Oak Avenue, Oakville, ON',
      Email: 'aliceosj@example.com',
      location: 'Oakville, ON',
      Subscription: false,
      PayFrequencySub: null,
      NextSubMaintdDate: null,
      TransactionValue: 999.99,
      TermsAgreed: 'Agreed to the extended service terms.',
      TransactionRefNum1: 'TRANS67890',
      TransactionRefNum2: 'ALT67890',
      ProvinceID:'Cundinamarca', 
      CityID:'Bogotá'
    },
    {
      Name: 'Bob Browns',
      Phone: '444-555-6666',
      Address: '321 Pine Lane, Hamilton, ON',
      Email: 'bobbos@example.com',
      location: 'Hamilton, ON',
      Subscription: false,
      PayFrequencySub: null,
      NextSubMaintdDate: null,
      TransactionValue: 129.99,
      TermsAgreed: 'Agreed to the standard terms and conditions.',
      TransactionRefNum1: 'TRANS98765',
      TransactionRefNum2: null,
          ProvinceID:'Cundinamarca', 
      CityID:'Bogotá'
    },
    {
      Name: 'Charlie Whites',
      Phone: '333-222-1111',
      Address: '654 Maple Road, Brampton, ON',
      Email: 'charliesw@example.com',
      location: 'Brampton, ON',
      Subscription: false,
      PayFrequencySub: null,
      NextSubMaintdDate: null,
      TransactionValue: 249.99,
      TermsAgreed: 'Agreed to the premium service terms.',
      TransactionRefNum1: 'TRANS24680',
      TransactionRefNum2: 'ALT24680',
          ProvinceID:'Cundinamarca', 
      CityID:'Bogotá'
    },
    {
      Name: 'Emily Davison',
      Phone: '222-333-4444',
      Address: '111 Birch Way, Waterloo, ON',
      Email: 'emilysd@example.com',
      location: 'Waterloo, ON',
      Subscription: false,
      PayFrequencySub: null,
      NextSubMaintdDate: null,
      TransactionValue: 99.99,
      TermsAgreed: 'Agreed to the standard terms and conditions.',
      TransactionRefNum1: 'TRANS13579',
      TransactionRefNum2: null,
          ProvinceID:'Cundinamarca', 
      CityID:'Bogotá'
    },
    {
      Name: 'Frankie Green',
      Phone: '666-777-8888',
      Address: '222 Cedar Street, Guelph, ON',
      Email: 'frankieg@example.com',
      location: 'Guelph, ON',
      Subscription: false,
      PayFrequencySub: null,
      NextSubMaintdDate: null,
      TransactionValue: 349.99,
      TermsAgreed: 'Agreed to the extended service terms.',
      TransactionRefNum1: 'TRANS11223',
      TransactionRefNum2: 'ALT11223',
          ProvinceID:'Cundinamarca', 
      CityID:'Bogotá'
    },
    {
      Name: 'Grace Blacks',
      Phone: '111-222-3333',
      Address: '333 Spruce Avenue, London, ON',
      Email: 'grace55b@example.com',
      location: 'London, ON',
      Subscription: false,
      PayFrequencySub: null,
      NextSubMaintdDate: null,
      TransactionValue: 179.99,
      TermsAgreed: 'Agreed to the standard terms and conditions.',
      TransactionRefNum1: 'TRANS44556',
      TransactionRefNum2: null,
          ProvinceID:'Cundinamarca', 
      CityID:'Bogotá'
    },
    {
      Name: 'Hanks Yellow',
      Phone: '999-888-7777',
      Address: '444 Aspen Drive, Windsor, ON',
      Email: 'hankyss@example.com',
      location: 'Windsor, ON',
      Subscription: false,
      PayFrequencySub: null,
      NextSubMaintdDate: null,
      TransactionValue: 599.99,
      TermsAgreed: 'Agreed to the premium service terms.',
      TransactionRefNum1: 'TRANS77889',
      TransactionRefNum2: 'ALT77889',
          ProvinceID:'Cundinamarca', 
      CityID:'Bogotá'
    },
  ]


  module.exports={teachingOrdersArr,MaintOrdeArr}