const myproductlist = [
   
            {
              ProductGroupID: 'GRP001',
              CategoryID: "electronics",
              ProductName: 'Smartphone X10',
              product_description: 'A high-performance smartphone with a sleek design.',             
              PackageWidth: 10.5,
              PackageHeight: 18.2,
              PackageLength: 5.0,
              PackageWeight: 0.8,
              ProductWidth: 7.5,
              ProductHeight: 15.0,
              ProductLength: 1.0,
              ProductWeight: 0.4,
              PreviousProduct: null,
              Obsolete: false,
              photos:['photo1.jpg','photo2.jpg']
            },
            {
              ProductGroupID: 'GRP002',            
              CategoryID: 'men clothing',
              ProductName: 'Men’s T-Shirt',
              product_description: 'A comfortable cotton t-shirt for men.',             
              PackageWidth: 12.0,
              PackageHeight: 1.5,
              PackageLength: 15.0,
              PackageWeight: 0.3,
              ProductWidth: 12.0,
              ProductHeight: 0.5,
              ProductLength: 14.0,
              ProductWeight: 0.2,
              PreviousProduct: null,
              Obsolete: false,
              photos:['photo3.jpg','photo4.jpg']
            },    
            {
              ProductGroupID: 'GRP003',            
              CategoryID: 'Home',
              ProductName: 'LED Lamp',
              product_description: 'Energy-efficient LED lamp for home and office use.',
              Price: 25.99,
              Stock: 80,
              PackageWidth: 15.0,
              PackageHeight: 25.0,
              PackageLength: 15.0,
              PackageWeight: 1.2,
              ProductWidth: 14.0,
              ProductHeight: 24.0,
              ProductLength: 14.0,
              ProductWeight: 1.0,
              PreviousProduct: null,
              Obsolete: false,
              photos:['photo5.jpg','photo6.jpg']
            },
            {
              ProductGroupID: 'GRP004',
              CategoryID: 'Sports',
              ProductName: 'Yoga Mat',
              product_description: 'Non-slip yoga mat for home workouts.',
              PackageWidth: 10.0,
              PackageHeight: 10.0,
              PackageLength: 60.0,
              PackageWeight: 2.0,
              ProductWidth: 10.0,
              ProductHeight: 10.0,
              ProductLength: 60.0,
              ProductWeight: 2.0,
              PreviousProduct: null,
              Obsolete: false,
              photos:['photo7.jpg','photo8.jpg']
            },
            {
              ProductGroupID: 'GRP005',
              CategoryID: 'Books',
              ProductName: 'Fiction Bestseller',
              product_description: 'A thrilling novel from a best-selling author.',
              PackageWidth: 15.0,
              PackageHeight: 3.0,
              PackageLength: 22.0,
              PackageWeight: 0.5,
              ProductWidth: 15.0,
              ProductHeight: 3.0,
              ProductLength: 22.0,
              ProductWeight: 0.5,
              PreviousProduct: null,
              Obsolete: false,
              photos:['photo9.jpg']
            },
    {
      ProductGroupID: 'GRP007',
      CategoryID: 'Beauty',
      ProductName: 'Moisturizing Cream',
      product_description: 'Hydrating cream for all skin types.',
      PackageWidth: 8.0,
      PackageHeight: 8.0,
      PackageLength: 8.0,
      PackageWeight: 0.5,
      ProductWidth: 7.5,
      ProductHeight: 7.5,
      ProductLength: 7.5,
      ProductWeight: 0.4,
      PreviousProduct: null,
      Obsolete: false,
      photos:['photo10.jpg']
      
    },
   {
      ProductGroupID: 'GRP008',
      CategoryID: 'Health',
      ProductName: 'Vitamin D Supplements',
      product_description: 'Daily vitamin D capsules for bone health.',
      PackageWidth: 5.0,
      PackageHeight: 5.0,
      PackageLength: 10.0,
      PackageWeight: 0.3,
      ProductWidth: 4.5,
      ProductHeight: 4.5,
      ProductLength: 9.5,
      ProductWeight: 0.25,
      PreviousProduct: null,
      Obsolete: false,
      photos:['photo11.jpg']
    },
    {
      ProductGroupID: 'GRP009',
      CategoryID: 'Toys',
      ProductName: 'Building Blocks Set',
      product_description: 'Colorful building blocks for kids aged 3+.',
      PackageWidth: 25.0,
      PackageHeight: 15.0,
      PackageLength: 30.0,
      PackageWeight: 1.8,
      ProductWidth: 24.0,
      ProductHeight: 14.0,
      ProductLength: 29.0,
      ProductWeight: 1.5,
      PreviousProduct: null,
      Obsolete: false,
      photos:[
        'photo12.jpg',
        'photo13.jpg',
        'photo14.jpg'

      ]
    },
    {
      ProductGroupID: 'GRP010',
      CategoryID: 'Other',
      ProductName: 'Portable USB Fan',
      product_description: 'Compact USB-powered fan for personal use.',
      PackageWidth: 12.0,
      PackageHeight: 5.0,
      PackageLength: 15.0,
      PackageWeight: 0.6,
      ProductWidth: 11.0,
      ProductHeight: 4.5,
      ProductLength: 14.5,
      ProductWeight: 0.5,
      PreviousProduct: null,
      Obsolete: false,
      photos:['photo15.jpg']
    },
    {
      ProductGroupID: 'GRP011',
      CategoryID: 'electronics',
      ProductName: 'Wireless Earbuds',
      product_description: 'High-quality wireless earbuds with noise cancellation.',
      PackageWidth: 10.0,
      PackageHeight: 5.0,
      PackageLength: 10.0,
      PackageWeight: 0.4,
      ProductWidth: 9.0,
      ProductHeight: 4.5,
      ProductLength: 9.0,
      ProductWeight: 0.35,
      PreviousProduct: null,
      Obsolete: false,
      photos:['photo16.jpg']
    },
    {
      ProductGroupID: 'GRP012',
      CategoryID: 'women clothing',
      ProductName: 'Women’s Jeans',
      product_description: 'Stylish and comfortable jeans for women.',
      PackageWidth: 30.0,
      PackageHeight: 4.0,
      PackageLength: 40.0,
      PackageWeight: 1.2,
      ProductWidth: 28.0,
      ProductHeight: 3.5,
      ProductLength: 38.0,
      ProductWeight: 1.0,
      PreviousProduct: null,
      Obsolete: false,
      photos:['photo17.jpg',
    'photo18.jpg',
    'photo19.jpg'
      ]
    },


]

module.exports = myproductlist;